networks:
  net:
    driver: bridge

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - chroma_data:/chroma
    networks:
      - net

volumes:
  chroma_data:
    driver: local
